### ISSUE TITLE
Do you have a model trained in the ADE20k dataset

### ISSUE THREAD

**Issue by zd19901107** [Eromera/erfnet_pytorch#16]
Do you have a model trained in the ADE20k dataset?

**Comment by RomelTorres** [comment]
I am interested in that too

**Comment by Eromera** [comment]
Hi! I don't have a model trained in ADE20k since the focus of my research are automotive scenarios like Cityscapes. However it would be easy to add a dataset loader in the code for ADE20K and test with it. We have a colleague in the laboratory that has successfully trained with ADE20K and is currently reporting very good results with ERFNet and minor variations, so I encourage you to try!
