### ISSUE TITLE
clarify "dropprob=0.03"

### ISSUE THREAD

**Issue by amiltonwong** [Eromera/erfnet_pytorch#42]
Hi, @Eromera 
Inside Encoder, the first five "non_bt_1D" [here](https://github.com/Eromera/erfnet_pytorch/blob/master/train/erfnet.py#L73) applies `dropprob=0.03`, it that correct? or just a typo which should be 0.3?

THX!

**Comment by Eromera** [comment]
Hi @amiltonwong, these values are right, they come from the torch version as well. This is done because initial layers receive fewer updates so its better to drop neurons at a lower rate here. But feel free to try different values, amount of hyperparameters is almost infinite so we weren't able to test all of them and their effect.
