### ISSUE TITLE
iouEval

### ISSUE THREAD

**Issue by boundles** [Eromera/erfnet_pytorch#9]
Hi, I don't understand  "fpmult = x_onehot * (1-y_onehot-ignores) ". Why it's not "fpmult = x_onehot * (1-y_onehot)"?

**Comment by Eromera** [comment]
Hi! ignores should be removed from the False-Positive count for the following reason:
In y_onehot you have a 1 for the class that is true and 0s for the rest of the classes. In the case where a pixel is set to ignore, all classes labels are 0 (y[0:18]==0) and the ignore class 19 is set to 1 (y[19]==1). Therefore, when applying 1-y_onehot to calculate false positives and one of the pixel is set to ignore, you are actually counting a 1 more than you should, because 1-y equals 1 for all 0 to 18 classes and when multiplied to x_onehot you are always getting a 1 regardless of the true class. Since ignore label should not be counted in the IoU metric because those pixels are not considered in the Cityscapes challenge, the IoU calculation that is equivalent to the one in the Cityscapes benchmark is by removing those ignore values (y_onehot[19]).

**Comment by boundles** [comment]
ok,I see, many thanks!
